#!/usr/bin/env bash

set -euo pipefail

MAIL_D="/var/mail/${LOGNAME}"

export PAGER=${CHECKMAIL_PAGER:-${PAGER:-more}}

usage_exit() {
	echo "Usage: $0 [<mailbox_command> [<arguments...>]]"
	exit "${1:-0}"
}

find_mailboxes_with_new_mail() {
	find "${MAIL_D}" -type d -not -empty \( -name 'new' -o -name 'cur' \) -print0 |
		xargs -0 -I{} -- find {} -type f -not -regex '.*,D?R?S[a-z]*' -printf '%h\n' |
		sed -E -e 's:^'"${MAIL_D}"'/:+:' -e 's:/?(cur|new)$::' |
		sort -u
}

get_mailbox_name() {
	if [[ "$1" = "+" ]]; then
		echo "INBOX"
	else
		echo "${1#+.}"
	fi
}

[[ "${1:-}" = "--help" ]] && usage_exit 0

mailbox_command=("$@")

if [[ ! -d "${MAIL_D}/cur" ]]; then
	echo "Maildir \"${MAIL_D}\" not found!" >&2
	exit 1
fi

if [[ -z "${mailbox_command[0]:-}" ]]; then
	if command -v s-nail >/dev/null 2>&1; then
		mailbox_command=("s-nail")
	else
		mailbox_command=("mail")
	fi
fi
if ! command -v "${mailbox_command[0]}" >/dev/null 2>&1; then
	echo "Command not found: \"${mailbox_command[0]}\"!"
	exit 1
fi

echo "Looking for new mail in ${MAIL_D} ..."

declare -i invocations=0
mapfile -t mailboxes < <(find_mailboxes_with_new_mail)

if [[ ${#mailboxes[@]} -eq 0 ]]; then
	echo "No new mail."
	exit 0
fi

for mailbox in "${mailboxes[@]}"; do
	printf " • \e[1m%s\e[0m\n" "$(get_mailbox_name "$mailbox")"
done

declare -i exit_code=0
for mailbox in "${mailboxes[@]}"; do
	printf '\nOpening "\e[1m%s\e[0m" with %s:\n' \
		"$(get_mailbox_name "$mailbox")" "${mailbox_command[0]}"
	invocations=$((invocations + 1))
	"${mailbox_command[@]}" -f "${mailbox}" && exit_code=0 || exit_code=$?
	[[ $exit_code -eq 0 ]] || break
done
echo

if [[ ${#mailboxes[@]} -ne $invocations ]]; then
	total_info=" (out of ${#mailboxes[@]})"
else
	total_info=""
fi
if [[ $invocations -eq 1 ]]; then
	mailbox_info="one mailbox"
else
	mailbox_info="$invocations mailboxes"
fi
echo "Called \"${mailbox_command[0]}\" on ${mailbox_info}${total_info} with unread mail."
exit $exit_code
